before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: CIQKZhm1kY1CidIXtV/+mcOlWSdAZdB0mGb8yI2shb6YuHPNdUyqp7hz4ymc4H3bKkbUjOr38YWAXt2Xkq63hy3ZC4Fe6qu8dw/f3dfUKv5vP9XC70tTye1iiglVj1hGspc24vlRpYe1jkVX5T2bHJJtRAnoz0PGZfi9jxoPKAIvfxzrehOw2BlSQLow4OWAd5tWPwPI8X8VfOMjiSuDHZCnaI5bjuDIhEIzTSZzzlocedJQ9Qzd/505Emaq6QQyC2pIItjG6FH4oxB9H2K371RqtRB6iS6n52RUzrONwzNeBC9ZnPCWV4ab/NO7FHjoYD82cQNQVmdvWchKpkkTUqZ1VMpL8N6CFYThOnEf3gbsb1XUsmR3nu/OiOYWWr4JWmeNpBI7MzRUvyUZRAOiHw5/CIjH56lrTaN+H8d6aH81voiW4IkL4rFuhBM/ncbWgCmtFN94vjU/S8xZdolP2vp1Dda6HwLat0jnxDbj6PCdCfWbLPWCEk7ybslW2CuqiF0mPH9uO6kRGThBsoBm1OPj8lxvSwW1ZNLgFcbR/V05OH8hTm80JS2BaJQ5USI2PYuEd1CghWX8q6uTWpnx/9HEqEXClKpOBhpHL/dmHPWPqLhvnUA9TY7TpvmbC9SpG2TZgo25rha44k/hgcaAvof4Q2jqetGQKUhUileWAFA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
